[package]
name = "reywen"
version = "0.1.10"
edition = "2021"
description = "A fast and simple framework for creating bots for revolt.chat"
license = "GPL-3.0-only"
documentation = "https://docs.rs/reywen/latest/reywen/"


[dependencies]

# serde
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
optional_struct = "0.2.0"
validator = { version = "0.16.0", features = ["derive"] }

# async
tokio = { version = "1.25.0", features = ["full"] }
futures-util = { version = "0.3.26", default-features = false, features = ["sink", "std"] }

# https
rand = "0.8.5"
reqwest = { version = "0.11", features = ["json", "native-tls"] }
iso8601-timestamp = "0.2.10"

# websocket
tokio-tungstenite = { version = "0.18.0", features = ["native-tls"] }
log = "0.4.17"


[profile.release]
opt-level = 3
debug = false
debug-assertions = false
lto = "thin"
