[package]
name = "reywen"
version = "0.1.14"
edition = "2021"
description = "A fast and simple framework for creating bots for revolt.chat"
license = "GPL-3.0-only"
documentation = "https://docs.rs/reywen/latest/reywen/"


[dependencies]

# revolt compat
iso8601-timestamp = "0.2.10"
validator = "0.16.0"
num_enum = "0.6.0"
indexmap = { version = "2.0.0", features = ["serde"] }

# data
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.95"

# misc
util = "0.1.3"
rand = "0.8.5"

# http
reywen_http = { version = "0.1.13", features = ["serde"] }
tokio-tungstenite = { version = "0.19.0", features = ["native-tls"] }

# async
tokio = { version = "1.27.0", features = ["full"] }
futures-util = "0.3.28"



[profile.release]
opt-level = 3
debug = false
debug-assertions = false
lto = "thin"
