[package]
name = "reywen2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json", "native-tls"] }

serde_json="*"
serde = { version = "1.0", features = ["derive"] }

optional_struct = "*"

validator = { version = "0.14", features = ["derive"] }


tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "*", features = ["native-tls"]}

futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }

futures-channel = "0.3"

tokio-net = "*"
rand = "0.8.5"
bson = "*"
mongodb = "*"
urlencoding = "2.1.2"


[profile.release]
opt-level = 3
debug = false
debug-assertions = false
lto = "fat"
